### ISSUE TITLE
cmseek is trying to write in the wrong directory

### ISSUE THREAD

**Issue by noraj** [Tuhinshubhra/CMSeeK#76] opened 2019-07-08 23:29 UTC
```
cmseek -u http://10.x.x.x/wp/
[i] Updating CMSeeK result index...
[x] Result directory does not exist!
There was an error while creating result index! Some features might not work as intended. Press [ENTER] to continue:
```

cmseek is writing (or trying to write) in the install directory rather than in the working (current) directory.

For example mine is installed in the root protected directory `/usr/share/cmseek/`.

**Comment by Tuhinshubhra** [comment] 2019-07-13 19:53
the recent updates screwed up with the directory thingy I'll push an update to fix all of these as soon as i can

**Comment by noraj** [comment] 2019-07-15 21:16
Wouldn't have been better to close the issue **after** the patch is pushed?

**Comment by Tuhinshubhra** [comment] 2019-07-15 23:49
the issue is still open wdym?

**Comment by noraj** [comment] 2019-07-18 11:24
My bad I commented the wrong issue.

**Comment by Tuhinshubhra** [comment] 2019-10-05 01:51
hey @noraj can you try the latest push and lemme know if it's fixed?

**Comment by noraj** [comment] 2019-10-05 19:56
```
$ echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
320.f980563
```

```
$ cmseek -u www.edited.com
[i] Updating CMSeeK result index...
[x] Result directory does not exist!
There was an error while creating result index! Some features might not work as intended. Press [ENTER] to continue:
```

Seems not fixed.

**Comment by Tuhinshubhra** [comment] 2019-10-05 20:03
Does it happen on the first run only or every run?

**Comment by noraj** [comment] 2019-10-05 20:08
At every run.

**Comment by noraj** [comment] 2019-10-05 20:11
If you want to reproduce this on how it works for an operating system install.
Clone your repo in a root protected folder (eg /usr/bin/cmseek/) and create a wrapper `/usr/bin/cmseek`

```
$ #!/bin/sh
exec python3 /usr/share/cmseek/cmseek.py "$@"
```

Then call `cmseek`.

**Comment by Tuhinshubhra** [comment] 2019-10-05 20:16
I did, can you make sure that you run `cmseek` from a directory that is writable? The only way it can happen every time is if both cmseek.cmseek_dir (the install location) and os.getcwd() are not writable.

**Comment by noraj** [comment] 2019-10-05 20:29
`/usr/share/cmseek` (cmseek.cmseek_dir) is not writable but `/tmp` (os.getcwd()) is.

As I understand I should end in this case
![image](https://user-images.githubusercontent.com/16578570/66260420-b0f29080-e7be-11e9-94c6-7527f97bcebc.png)

Ok I got it. I was exiting cmseek before pressing enter so the result dir was never created and the error kept displaying. If I press enter and let the script run the error only display the 1st time.

https://github.com/Tuhinshubhra/CMSeeK/blob/f980563cfb377037b0ec1750f4bc20ea67434492/cmseek.py#L92-L98

But I don't understand why outputting this error is necessary the 1st time if in fact it can write in os.getcwd().

**Comment by Tuhinshubhra** [comment] 2019-10-05 20:33
well it's because during the first run in a directory other than the install location the "Result" directory is not present and the create index is called before the directory is made. It's intended.

Anyways i will be closing the issue now as it seems fixed. 
Thank you for helping me make the tool better.

**Closed** 2019-10-05 20:33 UTC
Labels: Fixed, bug
