### ISSUE TITLE
Couldn't find login form... CMSeeK is quitting

### ISSUE THREAD

**Issue by Mjunior1** [Tuhinshubhra/CMSeeK#100] opened 2020-04-28 01:00 UTC
I'm trying to run BruteForce on a WordPress address, but the following message is appearing.

```
[i] Checking for WordPress
[*] WordPress Confirmed... Checking for WordPress login form
[x] Couldn't find login form... CMSeeK is quitting



 CMSeeK says ~ vale
```

The site in question is WordPress and there is a wp-login page normally.

![image](https://user-images.githubusercontent.com/14778300/80435255-6b202580-88d2-11ea-9483-e4c05bc398a0.png)

**Comment by Tuhinshubhra** [comment] 2020-04-28 11:59
are you sure there is a wp-logn.php page and does it have a form?

**Comment by Mjunior1** [comment] 2020-04-28 16:17
> 
> 
> are you sure there is a wp-logn.php page and does it have a form?

Hi @Tuhinshubhra, yes. Yes, there is a wp-login page.

![image](https://user-images.githubusercontent.com/14778300/80511561-a19d8500-8952-11ea-8fb6-e93fcee71293.png)

**Comment by Tuhinshubhra** [comment] 2020-04-30 08:19
By the looks of it these are two different websites, in your previous ss it was ***.com and the second one it's ***.com.br

Are you certain this is an issue? cause i'm unable to reproduce.

**Comment by Mjunior1** [comment] 2020-05-02 15:28
Yes. See:

`https:// www. cook smart foods . com . br`

Please, join space.

**Comment by Tuhinshubhra** [comment] 2020-05-03 16:06
This website returns 403 on wp-login.php. This is the reason why cmseek is unable to bruteforce.

Closing issue now.

**Closed by Tuhinshubhra** 2020-05-03 16:06 UTC
