### ISSUE TITLE
Incorrect cms detection

### ISSUE THREAD

**Issue by 1moles** [Tuhinshubhra/CMSeeK#54] opened 2019-02-12 08:26 UTC
The source and header detection methods detect CMS by certain fields.If a page contains these fields, but they are not actually CMS related, the page could be mistaken for using the CMS. Such as google "wp-content", you will get a page that contains a lot of "wp-content".
![google_wp](https://user-images.githubusercontent.com/30206283/52621496-65fbd400-2ee2-11e9-95bf-4942d25b74d1.PNG)
![cms_detect](https://user-images.githubusercontent.com/30206283/52621711-f2a69200-2ee2-11e9-9959-f905ed751871.PNG)

**Comment by Tuhinshubhra** [comment] 2019-02-16 15:10
Yep this is actually a issue i've been meaning to fix for a long time.. I will fix it ASAP thanks for bringing it to my attention.

**Comment by Tuhinshubhra** [comment] 2019-05-08 11:10
Hey @1moles i have pushed a possible fix.. could you try it and confirm if the issue is fixed?

**Comment by Tuhinshubhra** [comment] 2019-05-08 11:11
Closing the issue but feel free to reopen if the issue was not fixed.
Thank you for your help in making CMSeeK better :)

**Closed by Tuhinshubhra** 2019-05-08 11:11 UTC
Labels: bug
